[test.sh] Assertion failed: first, expected success but got failure in: 'false'
[test.sh] Error in source(runtest/test.sh:): 'false' exited with status 1
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at expect_true(runtest/test.sh:)
[test.sh]  at assert(runtest/test.sh:)
[test.sh]  at assert_true(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh] Assertion failed: second, expected success but got failure in: 'false'
[test.sh] Error in source(runtest/test.sh:): 'false' exited with status 1
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at expect_true(runtest/test.sh:)
[test.sh]  at assert(runtest/test.sh:)
[test.sh]  at assert_true(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh] Assertion failed: test_01, expected success but got failure in: 'false'
[test.sh] Error in source(runtest/test.sh:): 'false' exited with status 1
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at expect_true(runtest/test.sh:)
[test.sh]  at assert(runtest/test.sh:)
[test.sh]  at assert_true(runtest/test.sh:)
[test.sh]  at test_01(runtest/test/do_test_assert_71.sh:)
[test.sh]  at run_test(runtest/test.sh:)
[test.sh]  at source(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at run_tests(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh] FAILED: test_01
[test.sh] Assertion failed: teardown_test, expected success but got failure in: 'false'
[test.sh] Error in source(runtest/test.sh:): 'false' exited with status 1
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at expect_true(runtest/test.sh:)
[test.sh]  at assert(runtest/test.sh:)
[test.sh]  at assert_true(runtest/test.sh:)
[test.sh]  at teardown_test(runtest/test/do_test_assert_71.sh:)
[test.sh]  at call_if_exists(runtest/test.sh:)
[test.sh]  at call_teardown_subshell(runtest/test.sh:)
[test.sh]  at source(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at call_teardown(runtest/test.sh:)
[test.sh]  at run_test_teardown_trap(runtest/test.sh:)
[test.sh]  at exit_trap(runtest/test.sh:)
[test.sh]  at run_test(runtest/test.sh:)
[test.sh]  at source(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at run_tests(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh] Assertion failed: teardown_test_suite, expected success but got failure in: 'false'
[test.sh] Error in source(runtest/test.sh:): 'false' exited with status 1
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at expect_true(runtest/test.sh:)
[test.sh]  at assert(runtest/test.sh:)
[test.sh]  at assert_true(runtest/test.sh:)
[test.sh]  at teardown_test_suite(runtest/test/do_test_assert_71.sh:)
[test.sh]  at call_if_exists(runtest/test.sh:)
[test.sh]  at call_teardown_subshell(runtest/test.sh:)
[test.sh]  at source(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh]  at subshell(runtest/test.sh:)
[test.sh]  at call_teardown(runtest/test.sh:)
[test.sh]  at run_tests(runtest/test.sh:)
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
[test.sh] Error in run_tests(runtest/test.sh:): '[[ $failures == 0 ]]' exited with status 1
[test.sh]  at main(runtest/test/do_test_assert_71.sh:)
